#!usr/bin/zsh

if [ -z $IN_NIX_SHELL ];then
    PATH="$HOME/.cargo/bin:$PATH" # Rust
    PATH="$HOME/bin:$PATH" # Self-compiled
    PATH="$PATH:$HOME/.local/share/npm/bin" # NPM trash
    PATH="$PATH:$HOME/.local/bin" # Pip
    PATH="$PATH:/opt/xilinx/Vivado/2018.3/bin"
    PATH="$PATH:/sbin:/usr/sbin"
    export PATH

    MANPATH="$MANPATH:$HOME/.local/share/npm/share/man"
    export MANPATH
fi

if [ -z $LIBCLANG_PATH ]; then
    LLVM_VER="8"
    export LIBCLANG_PATH="/usr/lib/llvm/${LLVM_VER}/lib64"
    export PATH="$PATH:/usr/lib/llvm/${LLVM_VER}/bin"
fi

export SSH_KEY_PATH="$HOME/.ssh/id_rsa"
export GPG_TTY=$(tty)

export HISTFILE=~/.zsh_history
export HISTSIZE=10000000
export SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false

export EDITOR='nvim'
export PAGER="less"

export CCACHE_DIR="/gentoo/ccache"
export GOPATH="$HOME/.cache/go"
export XDG_CONFIG_HOME="$HOME/.config"

# zplug
export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh
zplug "zplug/zplug", hook-build:"zplug --self-manage"
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "zdharma/history-search-multi-word", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:2
zplug "zsh-users/zsh-completions", defer:2
zplug "zsh-users/zsh-autosuggestions", defer:2
zplug "hlissner/zsh-autopair", defer:2
zplug "hcgraf/zsh-sudo"
zplug "chisui/zsh-nix-shell"
zplug "spwhitt/nix-zsh-completions", defer:2
zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
zplug load

# keybinds
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey "${terminfo[kdch1]}" delete-char
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey "^[[1;5C" forward-word
bindkey "^[[1;3C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[1;3D" backward-word
bindkey -s "^O" 'nvim $(sk -m)^M'

# Utility functions
function pupd() {
    local freeze="$(pip list --user --format=freeze --outdated)"
    if [ -z "${freeze}" ]; then
        echo "Nothing to do."
    else
        local pkgs="$(echo ${freeze} | cut -f 1 -d '\' | tr '\n' ' ')"
        pip install --user -U "${pkgs}"
    fi
}

function ldd() {
    /usr/bin/ldd ${@} \
    | grep so \
    | sed -e '/^[^\t]/ d' \
    | sed -e 's/\t//' \
    | sed -e 's/.*=..//' \
    | sed -e 's/ (0.*)//' \
    | sort \
    | uniq -c \
    | sort -n
}
# Some useful aliases
## Tmux
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
## Taskwarrior
alias t="task"
## Use bat instead of cat
alias cat="bat"
alias b="bat"
## Use exa instead of ls proper
alias l="exa -bhlF"
alias ls="exa -bhlF"
alias la="exa -bhlFa"
## Neat trick to monitor sync
alias sync="sync & watch -n 1 rg -e Dirty: /proc/meminfo"
## Wireguard
alias wg="sudo wg"
## Some utility aliases
alias pip="pip3"
alias v="nvim"
alias vim="nvim"
alias vi="nvim"
alias pass="gopass"
## Git
alias g="git"
alias ga="git add"
alias gaa="git add -A"
alias gap="git add --patch"
alias gaap="git add -A --patch"
alias gc="git commit"
alias gch="git checkout"
alias gcl="git clone"
alias gd="git difftool"
alias gf="git fetch --prune --all"
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias gs="git status --find-renames --show-stash"
alias gm="git merge"
alias gp="git push"
alias gpl="git pull --rebase"
alias gr="git rebase"
alias grsn="git rebase --exec 'git commit --amend --no-edit -n -S'"
## Cargo
alias c="cargo"
alias cb="cargo build"
alias cbr="cargo build --release"
alias cc="cargo check"
alias ccl="cargo clean"
alias cdoc="cargo doc"
alias clp="cargo clippy"
alias cr="cargo run"
alias crr="cargo run --release"
alias ct="cargo test"
alias ctr="cargo test --release"
## Xargo
alias xb="cargo xbuild"
alias xbr="cargo xbuild --release"
alias xc="cargo xcheck"
alias xl="cargo clean"
alias xd="cargo doc"
alias xcl="cargo xclippy"
alias xr="cargo xrun"
alias xrr="cargo xrun --release"
alias xt="cargo xtest"
alias xtr="cargo xtest --release"
## Portage
alias upd="sudo emerge --sync"
alias upg="sudo emerge -uDU --keep-going --with-bdeps=y @world"
alias dcl="sudo emerge -av --depclean"
alias ecl="sudo eclean-dist"
alias mnt="upd && upg && dcl && sudo emaint -f all && ecl"
## Repoman
alias rch="repoman -dx full"
alias rcm="repoman commit"
alias rma="repoman manifest"
## NPM trash
alias nupd="npm -g upgrade"
## Local updates
alias lupd="zplug update && nupd && pupd"

# added by travis gem
[ -f /home/bemeurer/.travis/travis.sh ] && source /home/bemeurer/.travis/travis.sh
