#!usr/bin/zsh

if [ -z $IN_NIX_SHELL ];then
    PATH="$HOME/.cargo/bin:$PATH" # Rust
    PATH="$HOME/bin:$PATH" # Self-compiled
    PATH="$PATH:$HOME/.local/bin"  # Pip
    PATH="$PATH:/opt/xilinx/Vivado/2018.3/bin"
    PATH="$PATH:/sbin:/usr/sbin"
    export PATH
fi

if [ -z $LIBCLANG_PATH ]; then
    export LIBCLANG_PATH="/usr/lib/llvm/8/lib64"
fi

export SSH_KEY_PATH="$HOME/.ssh/id_rsa"
export GPG_TTY=$(tty)

export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

export EDITOR='nvim'
export PAGER="less"

export CCACHE_DIR="/gentoo/ccache"
export GOPATH="$HOME/.cache/go"
#export PYCHARM_JDK="$(java-config -O)"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CURRENT_DESKTOP="Unity"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context time dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# zplug
export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh
zplug "zplug/zplug", hook-build:"zplug --self-manage"
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "zdharma/history-search-multi-word", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:2
zplug "zsh-users/zsh-completions", defer:2
zplug "zsh-users/zsh-autosuggestions", defer:2
zplug "hlissner/zsh-autopair", defer:2
zplug "hcgraf/zsh-sudo"
zplug "chisui/zsh-nix-shell"
zplug "spwhitt/nix-zsh-completions", defer:2
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
# Load theme file
#zplug "chisui/0d12bd51a5fd8e6bb52e6e6a43d31d5e", from:gist, as:theme, use:agnoster-nix.zsh-theme
zplug load

# keybinds
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey "${terminfo[kdch1]}" delete-char
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey "^[[1;5C" forward-word
bindkey "^[[1;3C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[1;3D" backward-word
bindkey -s "^O" 'nvim $(sk -m)^M'

# Some useful aliases
## Taskwarrior
alias t="task"
## Use bat instead of cat
alias cat="bat"
alias b="bat"
## Use exa instead of ls proper
alias l="exa -bhlF"
alias ls="exa -bhlF"
alias la="exa -bhlFa"
## Neat trick to monitor sync
alias sync="sync & watch -n 1 rg -e Dirty: /proc/meminfo"
## Wireguard
alias wg="sudo wg"
## Some utility aliases
alias pip="pip3"
alias v="nvim"
alias vim="nvim"
alias vi="nvim"
alias pass="gopass"
## Git
alias g="git"
alias ga="git add"
alias gaa="git add -A"
alias gap="git add --patch"
alias gaap="git add -A --patch"
alias gc="git commit"
alias gch="git checkout"
alias gcl="git clone"
alias gd="git difftool"
alias gf="git fetch --prune"
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias gs="git status --find-renames --show-stash"
alias gm="git merge"
alias gp="git push"
alias gpl="git pull --rebase"
alias gr="git rebase"
## Cargo
alias c="cargo"
alias cb="cargo build"
alias cbr="cargo build --release"
alias cc="cargo check"
alias ccl="cargo clean"
alias cdoc="cargo doc"
alias clp="cargo clippy"
alias cr="cargo run"
alias crr="cargo run --release"
alias ct="cargo test"
alias ctr="cargo test --release"
## Xargo
alias xb="cargo xbuild"
alias xbr="cargo xbuild --release"
alias xc="cargo xcheck"
alias xl="cargo clean"
alias xd="cargo doc"
alias xcl="cargo xclippy"
alias xr="cargo xrun"
alias xrr="cargo xrun --release"
alias xt="cargo xtest"
alias xtr="cargo xtest --release"
## Portage
alias upd="sudo emerge --sync"
alias upg="sudo emerge -uDU --keep-going --with-bdeps=y @world"
alias dcl="sudo emerge -av --depclean"
alias mnt="upd && upg && dcl && sudo emaint -f all"

# added by travis gem
[ -f /home/bemeurer/.travis/travis.sh ] && source /home/bemeurer/.travis/travis.sh
